import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuItems from "@/components/menuItems";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </head>
      <body className=''>
<nav className="flex justify-between w-[1200px] mx-auto bg-blue-950/65 backdrop-blur-md py-5 px-[100px] fixed top-0 left-0 right-0 border-b-2 border-amber-50">

<div>
 
</div>
            
<div className="">
  <ul className="flex gap-8 text-2xl" >
          <MenuItems title={'Home'}/>
          <MenuItems title={'Works'}/>
          <MenuItems title={'Skills'}/>
          <MenuItems title={'About'}/>
          <MenuItems title={'Contact'}/>

      </ul>
</div>
</nav>


        {children}
      </body>
    </html>
  );
}
